version: "3.5"
services:
  mysql:
    container_name: install_temporal-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    # Mac M1 解注此行
#    platform: linux/x86_64
    image: mysql:${MYSQL_VERSION}
    networks:
      - temporal-network
    ports:
      - 3306:3306
  temporal:
    container_name: install_temporal
    depends_on:
      - mysql
    environment:
      - DB=mysql
      - DB_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PWD=root
      - MYSQL_SEEDS=mysql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development_sql.yaml
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/install_temporal/config/dynamicconfig
  temporal-admin-tools:
    container_name: install_temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=install_temporal:7233
    image: temporalio/admin-tools:${TEMPORAL_VERSION}
    networks:
      - temporal-network
    stdin_open: true
    tty: true
  temporal-web:
    container_name: install_temporal-web
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=install_temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    image: temporalio/web:${TEMPORAL_WEB_VERSION}
    networks:
      - temporal-network
    ports:
      - 8088:8088
networks:
  temporal-network:
    driver: bridge
    name: install_temporal-network
